name: Main
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  quality:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install tools
        run: |
          python -m pip install -U pip
          pip install pre-commit ruff
      - name: Pre-commit (cached)
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run pre-commit
        run: pre-commit run --all-files
      - name: Ruff lint
        run: ruff check .

  tests-and-type-check:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]  # include 3.12 so Codecov can run on it
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v3

      - name: Install Python + deps (dev group)
      # use the matrix version for Python
        run: |
          uv python install ${{ matrix.python-version }}
          uv sync --group dev

      - name: Tests (with coverage)
        env:
          # minimal env so app import doesn't crash in CI
          DEMO_MODE: "true"
          CB_BASE_URL: "http://localhost"
          CB_SECRET_NAME: "unit-test"
          DDB_TABLE: "unit-test"
          CACHE_TTL_SECONDS: "60"
          APP_NAME: "Iqana Demo"
          APP_VERSION: "0.0.0-ci"
          DEFAULT_USER_ID: "ci-user"
          WEB_ORIGIN: "http://localhost"
        run: uv run python -m pytest --cov --cov-config=pyproject.toml --cov-report=xml

      - name: Type-check
        run: uv run mypy

      - name: Upload coverage to Codecov (only on 3.12, if token present)
        if: matrix.python-version == '3.12' && secrets.CODECOV_TOKEN != ''
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
