name: Main
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  quality:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install tools
        run: |
          python -m pip install -U pip
          pip install pre-commit ruff
      - name: Pre-commit (cached)
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run pre-commit
        run: pre-commit run --all-files
      - name: Ruff lint
        run: ruff check .

  tests-and-type-check:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        # your pyproject requires >=3.10,<4.0, so drop 3.9
        python-version: ["3.10", "3.11"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install -U pip
          [ -f requirements.txt ] && pip install -r requirements.txt || true
          pip install -e .
          pip install pytest mypy coverage
      - name: Tests (coverage xml)
        run: uv run python -m pytest --cov --cov-config=pyproject.toml --cov-report=xml
      - name: Type-check
        run: mypy
      - name: Upload coverage to Codecov (runs only on 3.12 & if token present)
        if: matrix.python-version == '3.12' && env.CODECOV_TOKEN != ''
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        uses: codecov/codecov-action@v4
