name: release-main
on:
  release:
    types: [published]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to push to gh-pages with GITHUB_TOKEN
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install docs deps
        run: |
          python -m pip install -U pip
          pip install -e . mkdocs mkdocs-material mkdocs-github-admonitions-plugin mkdocstrings[python]
      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Deploy documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force
