name: python-ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Use uv (fast, lockfile-aware)
      - uses: astral-sh/setup-uv@v3

      - name: Install Python + deps (dev group)
        run: |
          uv python install 3.12
          uv sync --group dev

      - name: Lint
        run: uv run ruff check .

      - name: Tests (with coverage)
        run: uv run python -m pytest --cov --cov-config=pyproject.toml --cov-report=xml
